// <auto-generated />
using System;
using BemPromotora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BemPromotora.Migrations
{
    [DbContext(typeof(BemPromotoraContext))]
    partial class BemPromotoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BemPromotora.Models.Opcoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PerguntaFormularioId");

                    b.Property<string>("opcao");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaFormularioId");

                    b.ToTable("Opcoes");
                });

            modelBuilder.Entity("BemPromotora.Models.PerguntaFormulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pergunta");

                    b.HasKey("Id");

                    b.ToTable("PerguntaFormulario");
                });

            modelBuilder.Entity("BemPromotora.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Convenio");

                    b.Property<string>("FaixaIdade");

                    b.Property<string>("FaixaSalarial");

                    b.Property<string>("MotivoEmprestimo");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BemPromotora.Models.Opcoes", b =>
                {
                    b.HasOne("BemPromotora.Models.PerguntaFormulario")
                        .WithMany("Opcoes")
                        .HasForeignKey("PerguntaFormularioId");
                });
#pragma warning restore 612, 618
        }
    }
}
